# @package task
defaults:
  - nlp/default
  - override /dataset@_group_: nlp/question_answering/default
_target_: lightning_transformers.task.nlp.question_answering.QuestionAnsweringTransformer
downstream_model_type: transformers.AutoModelForQuestionAnswering
