name: Install pkg

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]  # windows-2019
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare env
        run: |
          pip install check-manifest "twine==3.2" setuptools wheel

      - name: Create package
        run: |
          check-manifest
          python setup.py sdist bdist_wheel

      - name: Check package
        run: |
          twine check dist/*
          python setup.py clean

      - name: Install | Uninstall package - archive
        run: |
          # install as archive
          pip install dist/*.tar.gz
          cd ..
          python -c "import lightning_transformers as lt; print(lt.__version__)"
          pip uninstall -y lightning_transformers

      - name: Install | Uninstall package - wheel
        run: |
          # install as wheel
          pip install dist/*.whl
          cd ..
          python -c "import lightning_transformers as lt; print(lt.__version__)"
          pip uninstall -y lightning_transformers
