defaults:
  - default # add args from default trainer conf
gpus: 1
accelerator: ddp
precision: 16
checkpoint_callback: False
limit_val_batches: 0
limit_test_batches: 0
callbacks:
  _target_: lightning_transformers.core.callback.CUDACallback
