# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.token_classification.TokenClassificationDataModule
cfg:
  task_name: ner
  dataset_name: conll2003
  preprocessing_num_workers: 1
  label_all_tokens: False
  pad_to_max_length: False
