# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.question_answering.datasets.SquadDataModule
cfg:
  dataset_name: squad
  dataset_config_name: 'plain_text'
  max_length: 384
  version_2_with_negative: False
  null_score_diff_threshold: .0
  doc_stride: 128
  n_best_size: 20
  max_answer_length: 30
  output_dir: ${training.output_dir}
