# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.summarization.XsumSummarizationDataModule
cfg:
  dataset_name: xsum
  max_source_length: 128
  max_target_length: 128
