# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.multiple_choice.RaceMultipleChoiceDataModule
cfg:
  dataset_name: race
  dataset_config_name: 'all'
  padding: False
